### ISSUE TITLE
음성파일 추출 방법

### ISSUE THREAD

**Issue by joojis** [CLUG-kr/ming#1]
동영상 파일에서 API에 전송하기 위해 음성파일을 추출하는 방법, 관련 라이브러리 등 조사

**Comment by rino0601** [comment]
ffmpeg로 될 것 같은데, 찾아볼게

근데 사람 목소리만 뽑아야 하능건가, 아니면 그냥 소리만 분리하면 되는 건가..?

**Comment by joojis** [comment]
@rino0601 우선은 소리만 분리, 음성을 분석해서 추가적인 정보를 얻는건 우선 나중 일. https://github.com/CLUG-kr/ming/issues/2

**Comment by joojis** [comment]
https://github.com/bramp/ffmpeg-cli-wrapper

**Comment by rino0601** [comment]
CLI 기능 넣고,
음성 변환 가능한것 확인하고 커밋함. 딱히 리뷰 필요 없어보여서 master에서 작업하고 바로 올림.
샘플레이트 조절이라던가, 시간 조절 필요하면 얘기 해주길, 일단 ffmpeg 자체는 지원하는걸로 알고 있음.

```
ming --test extract_sound "동영상파일" "저장위치"
```
로 사용 할 수 있음.

**Comment by rino0601** [comment]
아,  ffmpeg 설치하고, path 잡아야 동작합니다.

**Comment by joojis** [comment]
FFmpegBuilder에서 setStartOffset, setDuration을 사용하면 위치를 특정할 수 있음

**Comment by joojis** [comment]
https://github.com/CLUG-kr/ming/commit/ae50e64ad02d47f3b839619d621f182bb5986e7b
